server:
  port: 5566
spring:
  datasource:
    url: jdbc:mysql://192.168.26.184:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    xa:
      properties:
        useInformationSchema: true